apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripic-frontend
spec:
  selector:
    matchLabels:
      app: tripic-frontend
  template:
    metadata:
      labels:
        app: tripic-frontend
