apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- newTag: cb60d42c
- name: tkdgur1756/tri-pick
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
