apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: tkdgur1756/tri-pick
  newTag: 7f5402b7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
