apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripic-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 1 # Default to 10 if not specified
  selector:
    matchLabels:
      app: tripic-frontend
  template:
    metadata:
      labels:
        app: tripic-frontend
    spec:
      containers:
      - name: tripic-frontend
        image: tkdgur1756/tri-pick:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
