apiVersion: v1
kind: Service
metadata:
  name: tripick-frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: tripick-frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
